// Generated from evaluation/exceptions_dev.json of a real DEV run.
import type { ExceptionsResponse } from '@/types'

export const exceptionsData: ExceptionsResponse = {
  "items": [
    {
      "case_id": "CASE_00005",
      "payment_id": "PAY_00005",
      "type": "UNRESOLVED",
      "amount": 27192.08,
      "currency": "INR",
      "reason": "Unresolved: payment.order_id='ORD_00006' does not resolve to any known order, and no settlement directly references this payment. Relationship cannot be safely established.",
      "status": "UNRESOLVED",
      "priority": "LOW",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00007",
      "payment_id": "PAY_00007",
      "type": "DUPLICATE",
      "amount": 33831.55,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00006: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00016",
      "payment_id": "PAY_00016",
      "type": "MISSING_SETTLEMENT",
      "amount": 31159.38,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00021",
      "payment_id": "PAY_00021",
      "type": "MISSING_SETTLEMENT",
      "amount": 46977.04,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00027",
      "payment_id": "PAY_00027",
      "type": "MISSING_SETTLEMENT",
      "amount": 33513.2,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00033",
      "payment_id": "PAY_00033",
      "type": "DUPLICATE",
      "amount": 43285.47,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00032: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00035",
      "payment_id": "PAY_00035",
      "type": "AMBIGUOUS",
      "amount": 29041.11,
      "currency": "INR",
      "reason": "Unresolved: payment.order_id='ORD_00034' does not resolve to any known order, and no settlement directly references this payment. Relationship cannot be safely established.",
      "status": "UNRESOLVED",
      "priority": "LOW",
      "candidate_count": 1,
      "top_candidate_id": "STL_00049",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00044",
      "payment_id": "PAY_00044",
      "type": "UNRESOLVED",
      "amount": 34537.31,
      "currency": "INR",
      "reason": "Unresolved: payment.order_id='ORD_00043' does not resolve to any known order, and no settlement directly references this payment. Relationship cannot be safely established.",
      "status": "UNRESOLVED",
      "priority": "LOW",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00052",
      "payment_id": "PAY_00052",
      "type": "MISSING_SETTLEMENT",
      "amount": 42105.03,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00056",
      "payment_id": "PAY_00056",
      "type": "DUPLICATE",
      "amount": 37576.7,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00055: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00063",
      "payment_id": "PAY_00063",
      "type": "UNRESOLVED",
      "amount": 24433.13,
      "currency": "INR",
      "reason": "Unresolved: payment.order_id='ORD_00062' does not resolve to any known order, and no settlement directly references this payment. Relationship cannot be safely established.",
      "status": "UNRESOLVED",
      "priority": "LOW",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00073",
      "payment_id": "PAY_00073",
      "type": "DUPLICATE",
      "amount": 2753.03,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00072: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00088",
      "payment_id": "PAY_00088",
      "type": "DUPLICATE",
      "amount": 12993.74,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00087: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00090",
      "payment_id": "PAY_00090",
      "type": "MISSING_SETTLEMENT",
      "amount": 22186.75,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00102",
      "payment_id": "PAY_00102",
      "type": "AMBIGUOUS",
      "amount": 2776.55,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00091'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00091",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00103",
      "payment_id": "PAY_00103",
      "type": "AMBIGUOUS",
      "amount": 2775.53,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00091'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00091",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00105",
      "payment_id": "PAY_00105",
      "type": "DUPLICATE",
      "amount": 9165.93,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00104: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00110",
      "payment_id": "PAY_00110",
      "type": "AMBIGUOUS",
      "amount": 45575.54,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00097'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00097",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00111",
      "payment_id": "PAY_00111",
      "type": "AMBIGUOUS",
      "amount": 45574.95,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00097'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00097",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00114",
      "payment_id": "PAY_00114",
      "type": "MISSING_SETTLEMENT",
      "amount": 25338.84,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00126",
      "payment_id": "PAY_00126",
      "type": "MISSING_SETTLEMENT",
      "amount": 39537.87,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00127",
      "payment_id": "PAY_00127",
      "type": "MISSING_SETTLEMENT",
      "amount": 5941.35,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00144",
      "payment_id": "PAY_00144",
      "type": "DUPLICATE",
      "amount": 37432.53,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00143: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00148",
      "payment_id": "PAY_00148",
      "type": "AMBIGUOUS",
      "amount": 14827.63,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00126'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00126",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00149",
      "payment_id": "PAY_00149",
      "type": "AMBIGUOUS",
      "amount": 14826.15,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00126'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00126",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00162",
      "payment_id": "PAY_00162",
      "type": "DUPLICATE",
      "amount": 12763.31,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00161: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00169",
      "payment_id": "PAY_00169",
      "type": "AMBIGUOUS",
      "amount": 43881.44,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00146'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00146",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00170",
      "payment_id": "PAY_00170",
      "type": "AMBIGUOUS",
      "amount": 43880.16,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00146'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00146",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00171",
      "payment_id": "PAY_00171",
      "type": "UNRESOLVED",
      "amount": 48494.64,
      "currency": "INR",
      "reason": "Unresolved: payment.order_id='ORD_00165' does not resolve to any known order, and no settlement directly references this payment. Relationship cannot be safely established.",
      "status": "UNRESOLVED",
      "priority": "LOW",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00173",
      "payment_id": "PAY_00173",
      "type": "AMBIGUOUS",
      "amount": 3082.9,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00149'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00149",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00174",
      "payment_id": "PAY_00174",
      "type": "AMBIGUOUS",
      "amount": 3082.96,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00149'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00149",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00178",
      "payment_id": "PAY_00178",
      "type": "AMBIGUOUS",
      "amount": 2396.01,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00153'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00153",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00179",
      "payment_id": "PAY_00179",
      "type": "AMBIGUOUS",
      "amount": 2395.89,
      "currency": "INR",
      "reason": "Ambiguous: settlement candidate(s) ['STL_00153'] cannot be safely assigned - contested by another payment with an equal claim, and no reference evidence exists to arbitrate.",
      "status": "AMBIGUOUS",
      "priority": "MEDIUM",
      "candidate_count": 1,
      "top_candidate_id": "STL_00153",
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00185",
      "payment_id": "PAY_00185",
      "type": "DUPLICATE",
      "amount": 48745.4,
      "currency": "INR",
      "reason": "Duplicate of payment PAY_00184: same order/customer and amount within the duplicate detection window.",
      "status": "DUPLICATE",
      "priority": "MEDIUM",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    },
    {
      "case_id": "CASE_00188",
      "payment_id": "PAY_00188",
      "type": "UNRESOLVED",
      "amount": 49050.55,
      "currency": "INR",
      "reason": "Unresolved: payment.order_id='ORD_00182' does not resolve to any known order, and no settlement directly references this payment. Relationship cannot be safely established.",
      "status": "UNRESOLVED",
      "priority": "LOW",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Manual Review"
    },
    {
      "case_id": "CASE_00193",
      "payment_id": "PAY_00193",
      "type": "MISSING_SETTLEMENT",
      "amount": 14090.49,
      "currency": "INR",
      "reason": "Missing: no directly-referenced or amount/date-plausible settlement candidate found.",
      "status": "MISSING",
      "priority": "HIGH",
      "candidate_count": 0,
      "top_candidate_id": null,
      "ai_invoked": false,
      "recommended_action": "Confirm No Matching Record"
    }
  ],
  "summary": {
    "total": 36,
    "high_priority": 9,
    "review_required": 18,
    "unresolved": 6,
    "duplicates": 9
  }
} as unknown as ExceptionsResponse
